[package]
name = "lfs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
git2 = { path = "/Users/pavel.smirnov/Source/work/git2-rs", default-features = false, features = [
  "vendored-libgit2",
] }

[dev-dependencies]
tempfile = "3.23.0"
rstest = "0.26.1"
