[package]
name = "lfs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
git2 = { git = "https://github.com/pashokitsme/git2-rs", branch = "filter", default-features = false, features = [
  "vendored-libgit2",
] }
# git2 = { path = "/Users/pavel.smirnov/Source/work/git2-rs", default-features = false, features = [
#   "vendored-libgit2",
# ] }
hex = "0.4.3"
sha2 = "0.10.9"
thiserror = "2.0.17"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }

[dev-dependencies]
tracing-subscriber = "0.3.20"
assert_matches = "1.5.0"
assertables = "9.8.2"
tempfile = "3.23.0"
rstest = "0.26.1"
more-asserts = "0.3.1"
